import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { z } from "zod";
import { AdminSection } from "@/components/admin/section";
import { DateValue, Label, Money } from "@/components/dashboard/format";
import { Card, CardHeader, CardTitle } from "@/components/ui/card";
import { getAdminUser } from "@/server/admin/data";
export const metadata: Metadata = { title: "Admin user detail", description: "Read-only protected user account detail." };
export default async function AdminUserPage({ params }: { params: Promise<{ id: string }> }) { const parsed = z.string().uuid().safeParse((await params).id); if (!parsed.success) notFound(); const data = await getAdminUser(parsed.data); if (!data) notFound(); return <AdminSection title={data.profile.full_name} description="Read-only protected account context. No status or financial actions are available."><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{[["Status", data.profile.status], ["Country", data.profile.country ?? "—"], ["Phone", data.profile.phone ?? "—"], ["Created", new Intl.DateTimeFormat("en", { dateStyle: "medium" }).format(new Date(data.profile.created_at))]].map(([label,value]) => <Card key={label}><p className="text-sm text-muted">{label}</p><p className="mt-2 font-semibold capitalize">{value.replaceAll("_", " ")}</p></Card>)}</div>{data.wallets.length > 0 && <section className="mt-8"><h2 className="mb-4 text-xl font-semibold">Wallet accounts</h2><div className="grid gap-4 md:grid-cols-2">{data.wallets.map((wallet) => <Card key={wallet.id}><CardHeader><CardTitle>{wallet.currency}</CardTitle></CardHeader><dl className="grid grid-cols-2 gap-4 text-sm"><div><dt className="text-muted">Total</dt><dd><Money amount={wallet.total_balance} currency={wallet.currency} /></dd></div><div><dt className="text-muted">Available</dt><dd><Money amount={wallet.available_balance} currency={wallet.currency} /></dd></div><div><dt className="text-muted">Invested</dt><dd><Money amount={wallet.invested_amount} currency={wallet.currency} /></dd></div><div><dt className="text-muted">Earnings</dt><dd><Money amount={wallet.total_earnings} currency={wallet.currency} /></dd></div></dl></Card>)}</div></section>}{data.restrictions.length > 0 && <section className="mt-8"><h2 className="mb-4 text-xl font-semibold">Restrictions</h2><div className="grid gap-3">{data.restrictions.map((item) => <Card key={item.id}><div className="flex justify-between gap-4"><p className="font-semibold"><Label value={item.type} /></p><span className={item.active ? "text-warning" : "text-muted"}>{item.active ? "Active" : "Inactive"}</span></div><p className="mt-2 text-sm text-muted">{item.reason}</p></Card>)}</div></section>}{data.events.length > 0 && <section className="mt-8"><h2 className="mb-4 text-xl font-semibold">Security events</h2><div className="grid gap-3">{data.events.map((event) => <Card key={event.id}><div className="flex flex-wrap justify-between gap-3"><p><Label value={event.event_type} /></p><span className="text-sm capitalize text-muted">{event.severity}</span></div><p className="mt-2 text-xs text-muted"><DateValue value={event.created_at} /></p></Card>)}</div></section>}</AdminSection>; }
