import { test,expect } from "@playwright/test";
import AxeBuilder from "@axe-core/playwright";

test("public navigation, security headers, and responsive layout",async({page})=>{await page.goto("/");await expect(page.getByRole("heading",{level:1})).toBeVisible();await expect(page.locator("body")).not.toHaveCSS("overflow-x","scroll");const response=await page.request.get("/");expect(response.headers()["x-content-type-options"]).toBe("nosniff");expect(response.headers()["x-frame-options"]).toBe("DENY");expect(response.headers()["content-security-policy"]).toContain("frame-ancestors 'none'");});
test("mobile navigation opens and exposes its links",async({page},testInfo)=>{test.skip(testInfo.project.name!=="mobile","mobile project only");await page.goto("/");const toggle=page.getByRole("button",{name:/navigation/i});await toggle.click();await expect(toggle).toHaveAttribute("aria-expanded","true");await expect(page.locator("#mobile-navigation")).toBeVisible();});
test("login and registration forms are labelled",async({page})=>{await page.goto("/login");await expect(page.getByLabel("Email address")).toBeVisible();await expect(page.getByLabel("Password")).toHaveAttribute("type","password");await page.goto("/register");await expect(page.getByLabel("Full name")).toBeVisible();await expect(page.getByRole("checkbox")).toHaveCount(3);});
test("dashboard redirects unauthenticated visitors safely",async({page})=>{await page.goto("/dashboard");await expect(page).toHaveURL(/\/login\?redirectTo=%2Fdashboard|\/login\?redirectTo=\/dashboard/);});
test("public and auth pages have no critical automated accessibility violations",async({page})=>{for(const path of ["/","/login","/register","/faq"]){await page.goto(path);const results=await new AxeBuilder({page}).analyze();expect(results.violations.filter(v=>v.impact==="critical")).toEqual([]);}});
test("keyboard focus is visible and reaches primary navigation",async({page})=>{await page.goto("/");await page.keyboard.press("Tab");const focused=page.locator(":focus");await expect(focused).toBeVisible();const outline=await focused.evaluate(el=>getComputedStyle(el).outlineStyle);expect(outline).not.toBe("none");});
test("error and empty-state routes remain semantically usable",async({page})=>{await page.goto("/does-not-exist");await expect(page.getByRole("heading",{name:"Page not found"})).toBeVisible();await page.goto("/contact");await expect(page.getByRole("status")).toBeVisible();});
