import type { Metadata } from "next";
import Link from "next/link";
import { AuthMessage } from "@/components/auth/auth-message";
import { AuthShell } from "@/components/auth/auth-shell";
import { Button } from "@/components/ui/button";
import { Checkbox, Field, Input } from "@/components/ui/form-controls";
import { registerAction } from "@/server/auth/actions";
import { redirectAuthenticatedUser } from "@/server/auth/guards";
export const metadata: Metadata = { title: "Create an account", description: "Register for an Oryvane Capital user account and verify your email." };
export default async function RegisterPage({ searchParams }: { searchParams: Promise<{ error?: string }> }) { await redirectAuthenticatedUser(); const params = await searchParams; return <AuthShell eyebrow="User registration" title="Create your account" description="Complete the details below. Your email must be verified before protected financial features can become available." footer={<>Already registered? <Link className="text-emerald-strong hover:underline" href="/login">Log in</Link></>}><AuthMessage error={params.error} /><form action={registerAction} className="grid gap-5"><Field htmlFor="fullName" label="Full name"><Input id="fullName" name="fullName" autoComplete="name" maxLength={120} required /></Field><Field htmlFor="email" label="Email address"><Input id="email" name="email" type="email" autoComplete="email" maxLength={254} required /></Field><div className="grid gap-5 sm:grid-cols-2"><Field htmlFor="phone" label="Phone number"><Input id="phone" name="phone" type="tel" autoComplete="tel" maxLength={24} required /></Field><Field htmlFor="country" label="Country"><Input id="country" name="country" autoComplete="country-name" maxLength={80} required /></Field></div><Field htmlFor="password" label="Password" hint="12–72 characters, including upper-case, lower-case, number, and symbol."><Input id="password" name="password" type="password" autoComplete="new-password" minLength={12} maxLength={72} required /></Field><Field htmlFor="passwordConfirmation" label="Confirm password"><Input id="passwordConfirmation" name="passwordConfirmation" type="password" autoComplete="new-password" minLength={12} maxLength={72} required /></Field><fieldset className="grid gap-2"><legend className="mb-2 text-sm font-semibold">Required acknowledgements</legend><Checkbox name="termsAccepted" required label="I accept the Terms summary" /><Checkbox name="privacyAccepted" required label="I accept the Privacy summary" /><Checkbox name="riskAccepted" required label="I have read and accept the Risk Disclosure" /><p className="text-xs leading-5 text-muted">Review the <Link className="text-emerald-strong underline" href="/terms">Terms</Link>, <Link className="text-emerald-strong underline" href="/privacy">Privacy summary</Link>, and <Link className="text-emerald-strong underline" href="/risk-disclosure">Risk Disclosure</Link>.</p></fieldset><Button type="submit">Create account</Button></form></AuthShell>; }
