"use client";
import { animate, motion, useInView, useMotionValue, useReducedMotion, useTransform, type HTMLMotionProps } from "motion/react";
import { useEffect, useRef } from "react";

const easing = [0.16, 1, 0.3, 1] as const;
export function PageTransition(props: HTMLMotionProps<"div">) { const reduce = useReducedMotion(); return <motion.div initial={reduce ? false : { opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={reduce ? undefined : { opacity: 0, y: -6 }} transition={{ duration: reduce ? 0 : 0.32, ease: easing }} {...props} />; }
export function ScrollReveal(props: HTMLMotionProps<"div">) { const reduce = useReducedMotion(); return <motion.div initial={reduce ? false : { opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, margin: "-10%" }} transition={{ duration: reduce ? 0 : 0.42, ease: easing }} {...props} />; }
export function CardEntrance(props: HTMLMotionProps<"div">) { const reduce = useReducedMotion(); return <motion.div initial={reduce ? false : { opacity: 0, scale: 0.985, y: 12 }} whileInView={{ opacity: 1, scale: 1, y: 0 }} viewport={{ once: true }} transition={{ duration: reduce ? 0 : 0.32, ease: easing }} whileHover={reduce ? undefined : { y: -2 }} whileTap={reduce ? undefined : { scale: 0.995 }} {...props} />; }
export function NavigationTransition(props: HTMLMotionProps<"nav">) { const reduce = useReducedMotion(); return <motion.nav initial={reduce ? false : { opacity: 0, y: -8 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: reduce ? 0 : 0.28, ease: easing }} {...props} />; }
export function AnimatedFinancialFigure({ value, format = (current) => Math.round(current).toLocaleString(), className }: { value: number; format?: (value: number) => string; className?: string }) { const node = useRef<HTMLSpanElement>(null); const inView = useInView(node, { once: true }); const reduce = useReducedMotion(); const motionValue = useMotionValue(reduce ? value : 0); const rounded = useTransform(motionValue, format); useEffect(() => { if (!inView) return; const controls = animate(motionValue, value, { duration: reduce ? 0 : 0.7, ease: easing }); return controls.stop; }, [inView, motionValue, reduce, value]); return <motion.span ref={node} className={className} aria-label={format(value)}>{rounded}</motion.span>; }
