"use client";
import { BadgeDollarSign, ClipboardList, FileClock, LayoutDashboard, LogOut, Menu, ShieldCheck, TrendingUp, Users, WalletCards, X } from "lucide-react";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useState } from "react";
import { Button, buttonVariants } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import { adminLogoutAction } from "@/server/admin/auth-actions";
const items = [
  ["/admin", "Overview", "portal.access", LayoutDashboard], ["/admin/users", "Users", "users.view", Users], ["/admin/payments", "Payments", "payments.review", BadgeDollarSign], ["/admin/investments", "Investments", "investments.review", TrendingUp], ["/admin/withdrawals", "Withdrawals", "withdrawals.review", WalletCards], ["/admin/audit", "Audit log", "audit.view", FileClock],
] as const;
export function AdminNavigation({ role, permissions }: { role: string; permissions: string[] }) { const path = usePathname(); const [open, setOpen] = useState(false); const allowed = items.filter((item) => permissions.includes(item[2])); const nav = <><div className="border-b border-border p-5"><Link href="/admin" className="font-heading text-xl font-semibold">Oryvane <span className="text-gold">Control</span></Link><p className="mt-4 text-sm font-medium">{role}</p><p className="mt-1 flex items-center gap-1.5 text-xs text-emerald-strong"><ShieldCheck aria-hidden className="size-3.5" />AAL2 verified</p></div><nav aria-label="Admin portal" className="grid gap-1 p-3">{allowed.map(([href,label,,Icon]) => { const active = href === "/admin" ? path === href : path.startsWith(href); return <Link key={href} href={href} onClick={() => setOpen(false)} aria-current={active ? "page" : undefined} className={cn("flex min-h-11 items-center gap-3 rounded-md px-3 text-sm font-medium text-muted hover:bg-white/5 hover:text-foreground", active && "bg-gold/10 text-gold")}><Icon aria-hidden className="size-4" />{label}</Link>; })}</nav><div className="mt-auto border-t border-border p-3"><p className="mb-2 flex items-center gap-2 px-3 text-xs text-muted"><ClipboardList aria-hidden className="size-3.5" />Read-only foundation</p><form action={adminLogoutAction}><button className={cn(buttonVariants({ variant: "ghost" }), "w-full justify-start")} type="submit"><LogOut aria-hidden className="size-4" />Log out</button></form></div></>;
  return <><a href="#admin-content" className="sr-only focus:not-sr-only focus:fixed focus:left-4 focus:top-4 focus:z-[80] focus:rounded-md focus:bg-gold focus:px-4 focus:py-2 focus:text-background">Skip to admin content</a><header className="fixed inset-x-0 top-0 z-[40] flex h-16 items-center justify-between border-b border-border bg-background/95 px-4 backdrop-blur lg:hidden"><span className="font-heading font-semibold">Oryvane Control</span><Button type="button" size="icon" variant="secondary" aria-label={open ? "Close admin navigation" : "Open admin navigation"} aria-expanded={open} onClick={() => setOpen(!open)}>{open ? <X aria-hidden className="size-5" /> : <Menu aria-hidden className="size-5" />}</Button></header><aside className="sticky top-0 hidden h-screen flex-col border-r border-border bg-surface-subtle lg:flex">{nav}</aside>{open && <div className="fixed inset-0 z-[39] bg-black/70 lg:hidden" aria-hidden onClick={() => setOpen(false)} />}<aside className={cn("fixed inset-y-0 left-0 z-[40] flex w-[min(86vw,20rem)] flex-col border-r border-border bg-surface-subtle transition-transform motion-reduce:transition-none lg:hidden", open ? "translate-x-0" : "-translate-x-full")} aria-hidden={!open} inert={!open}>{nav}</aside></>;
}
