"use client";

import { motion, useReducedMotion } from "motion/react";
import { Bell, ChevronRight, CircleCheck, CreditCard, Eye, EyeOff, Fingerprint, LayoutDashboard, ReceiptText, Settings, ShieldCheck, TrendingUp, WalletCards } from "lucide-react";
import { useState } from "react";

import { Badge } from "@/components/ui/badge";

const summary = [["Total portfolio value", WalletCards], ["Available balance", CreditCard], ["Invested amount", TrendingUp], ["Total earnings", CircleCheck]] as const;
const nav = [["Overview", LayoutDashboard], ["Investments", TrendingUp], ["Transactions", ReceiptText], ["Security", ShieldCheck], ["Settings", Settings]] as const;

export function DashboardPreview() {
  const [hidden, setHidden] = useState(true);
  const [currency, setCurrency] = useState("USD");
  const reduce = useReducedMotion();
  const displayValue = hidden ? "••••••" : "—";

  return <div data-testid="portfolio-preview" aria-label="Illustrative premium account overview with masked financial values" className="cosmic-float mx-auto w-full max-w-6xl overflow-hidden rounded-3xl border border-border-strong bg-[#050a09]/96 shadow-[0_32px_90px_rgb(0_0_0/.44)]">
    <div className="flex flex-wrap items-center justify-between gap-2 border-b border-border px-4 py-2.5 sm:px-5"><div className="flex items-center gap-2"><span className="relative size-2 rounded-full bg-emerald"><span className="absolute inset-0 animate-ping rounded-full bg-emerald motion-reduce:animate-none"/></span><span className="text-sm font-semibold">Account overview</span></div><div className="flex items-center gap-2"><Badge>Interface preview</Badge><button type="button" aria-label="Notification controls" className="grid size-10 place-items-center rounded-lg border border-border text-muted hover:text-foreground"><Bell className="size-4"/></button></div></div>
    <div className="grid lg:grid-cols-[11rem_minmax(0,1fr)]"><aside className="border-b border-border bg-surface-subtle/75 p-3 lg:border-b-0 lg:border-r"><p className="px-2 font-reference text-[9px] uppercase tracking-[.2em] text-cyan">Portfolio control</p><nav aria-label="Preview dashboard navigation" className="mt-3 grid grid-cols-3 gap-1 sm:grid-cols-5 lg:grid-cols-1">{nav.map(([label, Icon], index) => <span key={label} className={`flex min-h-11 min-w-0 items-center justify-center gap-1.5 rounded-lg px-1.5 text-[10px] sm:text-xs lg:justify-start lg:px-2.5 ${index === 0 ? "bg-emerald/10 text-emerald-strong" : "text-muted"}`}><Icon className="size-3.5 shrink-0"/><span className="truncate">{label}</span></span>)}</nav><div className="mt-4 hidden rounded-xl border border-emerald/20 bg-emerald/[.06] p-3 lg:block"><ShieldCheck className="size-4 text-emerald-strong"/><p className="mt-3 text-xs font-semibold">Security active</p><p className="mt-1 text-[10px] leading-4 text-muted">Protected session controls.</p></div></aside>
      <div className="min-w-0 p-3 sm:p-5"><header className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-reference text-[9px] uppercase tracking-[.2em] text-muted">Private portfolio</p><h3 className="mt-1 text-xl font-semibold sm:text-2xl">Your financial position</h3><p className="mt-1 text-xs text-muted sm:text-sm">Values remain masked in this public interface preview.</p></div><div className="flex gap-2"><button type="button" onClick={() => setHidden(value => !value)} aria-pressed={!hidden} className="flex min-h-11 items-center gap-2 rounded-lg border border-border px-3 text-xs text-muted hover:text-foreground">{hidden ? <Eye className="size-4"/> : <EyeOff className="size-4"/>}{hidden ? "Reveal" : "Hide"}</button><select aria-label="Preview currency" value={currency} onChange={event => setCurrency(event.target.value)} className="min-h-11 rounded-lg border border-border bg-surface px-3 font-reference text-xs">{["USD", "EUR", "GBP", "NGN"].map(item => <option key={item}>{item}</option>)}</select></div></header>
        <section aria-label="Masked portfolio summaries" className="mt-4 grid grid-cols-2 gap-2.5 lg:grid-cols-4">{summary.map(([label, Icon], index) => <motion.article key={label} initial={reduce ? false : { opacity: 0, y: 10 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: index * .05 }} whileHover={reduce ? undefined : { y: -3 }} className="min-w-0 rounded-xl border border-border bg-[linear-gradient(145deg,rgb(14_28_24/.96),rgb(6_12_11/.96))] p-3 shadow-[0_14px_35px_rgb(0_0_0/.18)]"><div className="flex items-start justify-between gap-2"><p className="text-[10px] leading-4 text-muted sm:text-xs">{label}</p><Icon className="size-3.5 shrink-0 text-cyan"/></div><p className="mt-3 truncate font-reference text-lg tracking-wider sm:text-xl">{displayValue}</p><p className="mt-1 font-reference text-[8px] text-muted">{currency} · PRIVATE</p></motion.article>)}</section>
        <div className="mt-3 grid gap-3 lg:grid-cols-[.88fr_1.12fr]"><section className="rounded-xl border border-border bg-surface/78 p-4"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold">Portfolio allocation</p><p className="mt-0.5 text-[10px] text-muted">Verified holdings only</p></div><Badge tone="neutral">Masked</Badge></div><div className="mt-3 grid items-center gap-4 sm:grid-cols-[7rem_1fr] lg:grid-cols-[6rem_1fr]"><div className="relative mx-auto size-28 lg:size-24"><motion.div initial={reduce ? false : { rotate: -90, scale: .8 }} whileInView={{ rotate: 0, scale: 1 }} viewport={{ once: true }} className="size-full rounded-full bg-[conic-gradient(rgb(46_230_166/.3)_0_32%,rgb(80_213_255/.24)_32%_62%,rgb(217_183_110/.2)_62%_82%,rgb(255_255_255/.07)_82%)] p-3"><div className="grid size-full place-items-center rounded-full border border-border bg-background"><span className="font-reference text-base">••••</span></div></motion.div></div><div className="grid gap-2">{["Available funds", "Active investments", "Other verified holdings"].map((label, index) => <div className="flex items-center gap-2 text-[10px] text-muted sm:text-xs" key={label}><span className={`size-1.5 rounded-full ${index === 0 ? "bg-emerald" : index === 1 ? "bg-cyan" : "bg-gold"}`}/>{label}</div>)}<p className="mt-1 text-[9px] leading-4 text-muted">Decorative segmentation only; no allocation or return is represented.</p></div></div></section>
          <section className="rounded-xl border border-border bg-surface/78 p-4"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold">Account activity</p><p className="mt-0.5 text-[10px] text-muted">No fabricated records</p></div><ReceiptText className="size-4 text-gold"/></div><div className="mt-3 grid gap-1.5">{[["Active investments", "No preview records"], ["Pending deposits", "No pending actions"], ["Pending withdrawals", "No pending actions"], ["Recent transactions", "No preview transactions"]].map(([label, state]) => <div key={label} className="flex min-h-10 items-center justify-between gap-2 rounded-lg border border-border/70 bg-background/45 px-2.5"><span className="text-[10px] text-muted sm:text-xs">{label}</span><span className="flex items-center gap-1 text-right text-[10px] text-foreground sm:text-xs">{state}<ChevronRight className="size-3 shrink-0 text-muted"/></span></div>)}</div></section></div>
        <section className="mt-3 grid gap-2 sm:grid-cols-2"><div className="flex items-center gap-3 rounded-xl border border-emerald/20 bg-emerald/[.06] p-3"><motion.span animate={reduce ? undefined : { boxShadow: ["0 0 0 0 rgb(46 230 166 / .1)", "0 0 0 7px rgb(46 230 166 / 0)"] }} transition={{ repeat: Infinity, duration: 2 }} className="grid size-9 shrink-0 place-items-center rounded-full bg-emerald/12"><Fingerprint className="size-4 text-emerald-strong"/></motion.span><div><p className="text-xs font-semibold">Account verification</p><p className="mt-0.5 text-[10px] text-muted">Shown after secure sign-in</p></div></div><div className="flex items-center gap-3 rounded-xl border border-cyan/20 bg-cyan/[.05] p-3"><span className="grid size-9 shrink-0 place-items-center rounded-full bg-cyan/10"><ShieldCheck className="size-4 text-cyan"/></span><div><p className="text-xs font-semibold">Security status</p><p className="mt-0.5 text-[10px] text-muted">Available in account settings</p></div></div></section>
      </div></div>
  </div>;
}
