"use client";

import { motion, useReducedMotion } from "motion/react";
import { Bell, ChevronRight, CircleCheck, CreditCard, Eye, EyeOff, Fingerprint, LayoutDashboard, ReceiptText, Settings, ShieldCheck, TrendingUp, WalletCards } from "lucide-react";
import { useState } from "react";

import { Badge } from "@/components/ui/badge";

const summary = [["Total portfolio value", WalletCards], ["Available balance", CreditCard], ["Invested amount", TrendingUp], ["Total earnings", CircleCheck]] as const;
const nav = [["Overview", LayoutDashboard], ["Investments", TrendingUp], ["Transactions", ReceiptText], ["Security", ShieldCheck], ["Settings", Settings]] as const;

export function DashboardPreview() {
  const [hidden, setHidden] = useState(true);
  const [currency, setCurrency] = useState("USD");
  const reduce = useReducedMotion();
  const displayValue = hidden ? "••••••" : "—";

  return <div aria-label="Illustrative premium account overview with masked financial values" className="cosmic-float overflow-hidden rounded-3xl border border-border-strong bg-[#050a09]/96 shadow-[0_45px_120px_rgb(0_0_0/.5)]">
    <div className="flex flex-wrap items-center justify-between gap-3 border-b border-border px-4 py-3 sm:px-6"><div className="flex items-center gap-2"><span className="relative size-2 rounded-full bg-emerald"><span className="absolute inset-0 animate-ping rounded-full bg-emerald motion-reduce:animate-none"/></span><span className="text-sm font-semibold">Account overview</span></div><div className="flex items-center gap-2"><Badge>Interface preview</Badge><button type="button" aria-label="Notification controls" className="grid size-10 place-items-center rounded-lg border border-border text-muted hover:text-foreground"><Bell className="size-4"/></button></div></div>
    <div className="grid lg:grid-cols-[14rem_minmax(0,1fr)]"><aside className="border-b border-border bg-surface-subtle/75 p-4 lg:border-b-0 lg:border-r"><p className="px-3 font-reference text-[9px] uppercase tracking-[.2em] text-cyan">Portfolio control</p><nav aria-label="Preview dashboard navigation" className="mt-5 grid grid-cols-2 gap-1 lg:grid-cols-1">{nav.map(([label, Icon], index) => <span key={label} className={`flex min-h-11 items-center gap-3 rounded-xl px-3 text-sm ${index === 0 ? "bg-emerald/10 text-emerald-strong" : "text-muted"}`}><Icon className="size-4"/>{label}</span>)}</nav><div className="mt-6 hidden rounded-2xl border border-emerald/20 bg-emerald/[.06] p-4 lg:block"><ShieldCheck className="size-5 text-emerald-strong"/><p className="mt-5 text-sm font-semibold">Security active</p><p className="mt-1 text-xs leading-5 text-muted">Protected session and verified account controls.</p></div></aside>
      <div className="min-w-0 p-4 sm:p-6 lg:p-8"><header className="flex flex-wrap items-start justify-between gap-4"><div><p className="font-reference text-[10px] uppercase tracking-[.2em] text-muted">Private portfolio</p><h3 className="mt-2 text-2xl font-semibold sm:text-3xl">Your financial position</h3><p className="mt-2 text-sm text-muted">Values remain masked in this public interface preview.</p></div><div className="flex gap-2"><button type="button" onClick={() => setHidden(value => !value)} aria-pressed={!hidden} className="flex min-h-10 items-center gap-2 rounded-lg border border-border px-3 text-xs text-muted hover:text-foreground">{hidden ? <Eye className="size-4"/> : <EyeOff className="size-4"/>}{hidden ? "Reveal" : "Hide"}</button><select aria-label="Preview currency" value={currency} onChange={event => setCurrency(event.target.value)} className="min-h-10 rounded-lg border border-border bg-surface px-3 font-reference text-xs">{["USD", "EUR", "GBP", "NGN"].map(item => <option key={item}>{item}</option>)}</select></div></header>
        <section aria-label="Masked portfolio summaries" className="mt-7 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{summary.map(([label, Icon], index) => <motion.article key={label} initial={reduce ? false : { opacity: 0, y: 14 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: index * .06 }} whileHover={reduce ? undefined : { y: -5, rotateX: 1.5 }} className="rounded-2xl border border-border bg-[linear-gradient(145deg,rgb(14_28_24/.96),rgb(6_12_11/.96))] p-4 shadow-[0_20px_50px_rgb(0_0_0/.2)]"><div className="flex items-center justify-between gap-3"><p className="text-xs text-muted">{label}</p><Icon className="size-4 text-cyan"/></div><p className="mt-7 font-reference text-2xl tracking-wider">{displayValue}</p><p className="mt-2 font-reference text-[9px] text-muted">{currency} · PRIVATE</p></motion.article>)}</section>
        <div className="mt-5 grid gap-4 xl:grid-cols-[.9fr_1.1fr]"><section className="rounded-2xl border border-border bg-surface/78 p-5"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold">Portfolio allocation</p><p className="mt-1 text-xs text-muted">Based only on verified holdings</p></div><Badge tone="neutral">Masked</Badge></div><div className="mt-6 grid items-center gap-6 sm:grid-cols-[9rem_1fr]"><div className="relative mx-auto size-36"><motion.div initial={reduce ? false : { rotate: -90, scale: .8 }} whileInView={{ rotate: 0, scale: 1 }} viewport={{ once: true }} className="size-full rounded-full bg-[conic-gradient(rgb(46_230_166/.3)_0_32%,rgb(80_213_255/.24)_32%_62%,rgb(217_183_110/.2)_62%_82%,rgb(255_255_255/.07)_82%)] p-4"><div className="grid size-full place-items-center rounded-full border border-border bg-background"><span className="font-reference text-lg">••••</span></div></motion.div></div><div className="grid gap-3">{["Available funds", "Active investments", "Other verified holdings"].map((label, index) => <div className="flex items-center gap-3 text-xs text-muted" key={label}><span className={`size-2 rounded-full ${index === 0 ? "bg-emerald" : index === 1 ? "bg-cyan" : "bg-gold"}`}/>{label}</div>)}<p className="mt-2 text-[11px] leading-5 text-muted">Segments are decorative placeholders only; no allocation or return is represented.</p></div></div></section>
          <section className="rounded-2xl border border-border bg-surface/78 p-5"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold">Account activity</p><p className="mt-1 text-xs text-muted">Clear states without fabricated records</p></div><ReceiptText className="size-4 text-gold"/></div><div className="mt-5 grid gap-2">{[["Active investments", "No preview records"], ["Pending deposits", "No pending actions"], ["Pending withdrawals", "No pending actions"], ["Recent transactions", "No preview transactions"]].map(([label, state]) => <div key={label} className="flex min-h-11 items-center justify-between gap-3 rounded-xl border border-border/70 bg-background/45 px-3"><span className="text-xs text-muted">{label}</span><span className="flex items-center gap-1 text-xs text-foreground">{state}<ChevronRight className="size-3 text-muted"/></span></div>)}</div></section></div>
        <section className="mt-4 grid gap-3 sm:grid-cols-2"><div className="flex items-center gap-4 rounded-2xl border border-emerald/20 bg-emerald/[.06] p-4"><motion.span animate={reduce ? undefined : { boxShadow: ["0 0 0 0 rgb(46 230 166 / .1)", "0 0 0 9px rgb(46 230 166 / 0)"] }} transition={{ repeat: Infinity, duration: 2 }} className="grid size-10 place-items-center rounded-full bg-emerald/12"><Fingerprint className="size-5 text-emerald-strong"/></motion.span><div><p className="text-sm font-semibold">Account verification</p><p className="mt-1 text-xs text-muted">Status shown after secure sign-in</p></div></div><div className="flex items-center gap-4 rounded-2xl border border-cyan/20 bg-cyan/[.05] p-4"><span className="grid size-10 place-items-center rounded-full bg-cyan/10"><ShieldCheck className="size-5 text-cyan"/></span><div><p className="text-sm font-semibold">Security status</p><p className="mt-1 text-xs text-muted">Controls available in account settings</p></div></div></section>
      </div></div>
  </div>;
}
