import type { ReactNode } from "react";
import { PageTransition, ScrollReveal } from "@/components/motion/motion-system";
import { Badge } from "@/components/ui/badge";
import { cn } from "@/lib/utils";
import { MarketUniverse } from "@/components/market/market-universe";

export function PageShell({ children }: { children: ReactNode }) { return <PageTransition><main>{children}</main></PageTransition>; }
export function Container({ children, className }: { children: ReactNode; className?: string }) { return <div className={cn("mx-auto w-full max-w-[90rem] px-[var(--space-page)]", className)}>{children}</div>; }
export function PageHero({ eyebrow, title, description, children }: { eyebrow: string; title: string; description: string; children?: ReactNode }) { return <section className="terminal-noise relative overflow-hidden border-b border-border py-20 sm:py-28 lg:py-36"><MarketUniverse compact/><Container className="relative"><Badge tone="gold">{eyebrow}</Badge><h1 className="mt-7 max-w-5xl text-[clamp(2.8rem,7vw,6.8rem)] font-semibold leading-[.94] tracking-[-0.065em] text-balance">{title}</h1><p className="mt-7 max-w-2xl text-base leading-7 text-muted sm:text-xl sm:leading-8">{description}</p>{children && <div className="mt-9">{children}</div>}</Container></section>; }
export function PublicSection({ eyebrow, title, description, children, className }: { eyebrow?: string; title: string; description?: string; children: ReactNode; className?: string }) { return <section className={cn("relative py-20 sm:py-28", className)}><Container><ScrollReveal>{eyebrow && <p className="font-reference text-[11px] font-semibold uppercase tracking-[0.22em] text-cyan">{eyebrow}</p>}<h2 className="mt-4 max-w-4xl text-3xl font-semibold leading-[1.02] tracking-[-0.05em] text-balance sm:text-5xl lg:text-6xl">{title}</h2>{description && <p className="mt-6 max-w-2xl text-base leading-7 text-muted">{description}</p>}</ScrollReveal><div className="mt-12 sm:mt-16">{children}</div></Container></section>; }
