import type { Metadata } from "next";
import { ArrowRight, BookOpenCheck, FileCheck2, LockKeyhole, ScanSearch, ShieldCheck, WalletCards } from "lucide-react";
import Link from "next/link";

import { CallToAction } from "@/components/public/call-to-action";
import { DashboardPreview } from "@/components/public/dashboard-preview";
import { FaqList } from "@/components/public/faq-list";
import { FeatureGrid } from "@/components/public/feature-grid";
import { InvestmentCard } from "@/components/public/investment-card";
import { Container, PageShell, PublicSection } from "@/components/public/page-shell";
import { RiskNotice } from "@/components/public/risk-notice";
import { buttonVariants } from "@/components/ui/button";
import { commonQuestions, investmentFrameworks } from "@/content/public-content";

export const metadata: Metadata = { title: "Clarity for every investment decision", description: "Explore Oryvane Capital's planned investment experience, controlled operations, security approach, and risk-first information." };

export default function HomePage() { return <PageShell>
  <section className="relative overflow-hidden py-18 sm:py-28 lg:py-36"><div aria-hidden className="absolute inset-0 bg-[radial-gradient(circle_at_75%_25%,color-mix(in_srgb,var(--emerald)_13%,transparent),transparent_32%),linear-gradient(to_bottom,transparent,var(--background))]" /><Container className="relative"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-gold">Measured ambition. Visible control.</p><h1 className="mt-6 max-w-6xl text-5xl font-semibold leading-[0.98] tracking-[-0.055em] text-balance sm:text-7xl lg:text-[6.5rem]">Invest with clarity,<br /><span className="text-emerald-strong">not noise.</span></h1><p className="mt-7 max-w-2xl text-base leading-7 text-muted sm:text-xl sm:leading-8">Oryvane Capital is shaping a premium investment experience built around considered opportunities, transparent status, and protected financial operations.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/register" className={buttonVariants({ size: "lg" })}>Create account <ArrowRight aria-hidden className="size-4" /></Link><Link href="/investments" className={buttonVariants({ variant: "secondary", size: "lg" })}>Explore frameworks</Link></div><p className="mt-6 max-w-xl text-xs leading-5 text-muted">Platform financial functionality is not active yet. Public information is not financial advice or an offer to invest.</p></Container></section>
  <RiskNotice />
  <PublicSection eyebrow="The platform" title="A calmer way to understand your financial position." description="The intended experience separates clear user visibility from protected operational control."><FeatureGrid items={[{ icon: WalletCards, title: "One organised view", description: "Account figures, investments, transactions, and requests are designed to sit within a consistent information hierarchy." }, { icon: FileCheck2, title: "Traceable operations", description: "The planned workflow preserves financial and review history instead of silently overwriting important records." }, { icon: ScanSearch, title: "Human review where it matters", description: "Payment and withdrawal operations are designed around authorised review and explicit status communication." }]} /></PublicSection>
  <PublicSection className="bg-surface-subtle" eyebrow="Investment frameworks" title="Understand the approach before the terms." description="These are interface and information frameworks, not available products. Final assets, currencies, durations, limits, fees, and risk terms await approval."><div className="grid gap-4 md:grid-cols-3">{investmentFrameworks.map((framework) => <InvestmentCard framework={framework} key={framework.slug} />)}</div><Link href="/investments" className="mt-8 inline-flex min-h-11 items-center gap-2 text-sm font-semibold text-emerald-strong">View every framework <ArrowRight aria-hidden className="size-4" /></Link></PublicSection>
  <PublicSection eyebrow="How it works" title="A deliberate path from understanding to oversight."><ol className="grid gap-4 md:grid-cols-3">{[["01", "Review", "Explore available information, risks, and approved terms before making a decision."], ["02", "Submit", "When future functionality is active, requests and supporting information follow controlled workflows."], ["03", "Track", "Clear status and permanent records are intended to keep each step understandable."]].map(([number, title, description]) => <li className="border-t border-border pt-5" key={number}><span className="font-reference text-xs text-gold">{number}</span><h3 className="mt-5 text-2xl font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-muted">{description}</p></li>)}</ol></PublicSection>
  <PublicSection className="bg-surface-subtle" eyebrow="Security by structure" title="Trust needs more than a polished interface." description="Security is designed around separation of duties, private information boundaries, and protected server operations."><FeatureGrid items={[{ icon: LockKeyhole, title: "Protected operations", description: "Financial and administrative changes are intended to be authorised on the server, never trusted directly from browser controls." }, { icon: ShieldCheck, title: "Controlled access", description: "User and administrator boundaries are designed separately, with least-privilege permissions planned for sensitive operations." }, { icon: BookOpenCheck, title: "Accountable records", description: "Financial corrections are intended to use linked reversal records while preserving the original history." }]} /><Link className="mt-8 inline-flex min-h-11 items-center gap-2 text-sm font-semibold text-emerald-strong" href="/security">Read our security approach <ArrowRight aria-hidden className="size-4" /></Link></PublicSection>
  <PublicSection eyebrow="Interface preview" title="Information designed to be read, not decoded." description="This neutral preview demonstrates hierarchy only. It contains no user balance, investment performance, or activity data."><DashboardPreview /></PublicSection>
  <PublicSection className="bg-surface-subtle" eyebrow="Questions" title="Clear answers before action."><FaqList items={commonQuestions.slice(0, 4)} /><Link href="/faq" className="mt-7 inline-flex min-h-11 items-center gap-2 text-sm font-semibold text-emerald-strong">View all questions <ArrowRight aria-hidden className="size-4" /></Link></PublicSection>
  <CallToAction />
  </PageShell>; }
