import "server-only";
import { createClient } from "@/lib/supabase/server";
import { requireAdmin, requireAdminPermission } from "@/server/admin/authorization";

function ensure<T>(data: T | null, error: { message: string } | null, label: string): T { if (error || data === null) throw new Error(`Unable to load ${label}.`); return data; }
export async function getAdminOverview() { const context = await requireAdmin(); const supabase = await createClient(); const cards: Array<{ label: string; count: number; href: string }> = []; const specs = [
  ["users.view", "profiles", "Users", "/admin/users"], ["payments.review", "payment_submissions", "Payments", "/admin/payments"], ["investments.review", "user_investments", "Investments", "/admin/investments"], ["withdrawals.review", "withdrawal_requests", "Withdrawals", "/admin/withdrawals"], ["audit.view", "admin_audit_logs", "Audit events", "/admin/audit"],
] as const; for (const [permission, table, label, href] of specs) { if (!context.permissions.includes(permission)) continue; const result = await supabase.from(table).select("id", { count: "exact", head: true }); if (!result.error) cards.push({ label, count: result.count ?? 0, href }); } return { context, cards }; }
export async function getAdminUsers() { await requireAdminPermission("users.view"); const supabase = await createClient(); const result = await supabase.from("profiles").select("id, full_name, phone, country, status, created_at").order("created_at", { ascending: false }).limit(200); return ensure(result.data, result.error, "users"); }
export async function getAdminUser(id: string) { const context = await requireAdminPermission("users.view"); const supabase = await createClient(); const profile = await supabase.from("profiles").select("id, full_name, phone, country, status, created_at, updated_at").eq("id", id).maybeSingle(); if (profile.error) throw new Error("Unable to load user."); if (!profile.data) return null; const [wallets, restrictions, events] = await Promise.all([
  context.permissions.includes("finance.view") ? supabase.from("wallet_accounts").select("id, currency, total_balance, available_balance, invested_amount, total_earnings").eq("user_id", id) : Promise.resolve({ data: [], error: null }),
  context.permissions.includes("restrictions.manage") ? supabase.from("account_restrictions").select("id, type, reason, active, starts_at, expires_at").eq("user_id", id).order("created_at", { ascending: false }) : Promise.resolve({ data: [], error: null }),
  context.permissions.includes("security.view") ? supabase.from("security_events").select("id, user_id, event_type, severity, created_at").eq("user_id", id).order("created_at", { ascending: false }).limit(50) : Promise.resolve({ data: [], error: null }),
]); return { profile: profile.data, wallets: wallets.data ?? [], restrictions: restrictions.data ?? [], events: events.data ?? [] }; }
export async function getAdminUserOperations(id: string) { const context=await requireAdminPermission("users.view"); const supabase=await createClient(); const [transactions,notifications]=await Promise.all([context.permissions.includes("finance.view")?supabase.from("wallet_transactions").select("id,wallet_account_id,type,direction,amount,currency,reference,status,created_at").eq("user_id",id).order("created_at",{ascending:false}).limit(100):Promise.resolve({data:[],error:null}),context.permissions.includes("notifications.send")?supabase.from("notifications").select("id,type,title,body,created_at,read_at").eq("user_id",id).order("created_at",{ascending:false}).limit(50):Promise.resolve({data:[],error:null})]); return {context,transactions:transactions.data??[],notifications:notifications.data??[]}; }
export async function getAdminPayments() { await requireAdminPermission("payments.review"); const supabase = await createClient(); const result = await supabase.from("payment_submissions").select("id, internal_reference, method, submitted_amount, confirmed_amount, currency, external_reference, status, receipt_path, receipt_scan_status, receipt_scanned_at, rejection_reason, submitted_at, reviewed_at, credited_at, created_at, profiles(full_name)").order("created_at", { ascending: false }).limit(200); return ensure(result.data, result.error, "payments"); }
export async function getAdminInvestments() { await requireAdminPermission("investments.review"); const supabase = await createClient(); const result = await supabase.from("user_investments").select("id, amount, earnings_amount, currency, status, started_at, matures_at, created_at, profiles(full_name), investment_plans(name)").order("created_at", { ascending: false }).limit(200); return ensure(result.data, result.error, "investments"); }
export async function getAdminInvestmentPlans() { await requireAdminPermission("plans.view"); const supabase=await createClient(); const result=await supabase.from("investment_plans").select("id,slug,name,short_description,full_description,minimum_amount,maximum_amount,currency,duration_days,return_description,risk_level,terms,status").order("created_at",{ascending:false}).limit(100); return ensure(result.data,result.error,"investment plans"); }
export async function getAdminWithdrawals() { await requireAdminPermission("withdrawals.review"); const supabase = await createClient(); const result = await supabase.from("withdrawal_requests").select("id, internal_reference, amount, currency, method, destination, user_note, status, rejection_reason, submitted_at, paid_at, profiles(full_name)").order("submitted_at", { ascending: false }).limit(200); return ensure(result.data, result.error, "withdrawals"); }
export async function getAdminAudit() { await requireAdminPermission("audit.view"); const supabase = await createClient(); const result = await supabase.from("admin_audit_logs").select("id, admin_id, affected_user_id, action, resource_type, resource_id, reason, amount, currency, reference, created_at").order("created_at", { ascending: false }).limit(200); return ensure(result.data, result.error, "audit log"); }
