import { describe,expect,it } from "vitest";
import { registrationSchema,loginSchema } from "@/validation/auth";
import { paymentFormSchema,MAX_RECEIPT_BYTES } from "@/validation/payment";
import { investmentRequestSchema } from "@/validation/investment";
import { withdrawalSchema } from "@/validation/withdrawal";

describe("trusted input validation",()=>{
 it("accepts a compliant registration and rejects weak or mismatched passwords",()=>{const valid={fullName:"Ada Lovelace",email:"ADA@example.com",phone:"+234 800 000 0000",country:"Nigeria",password:"CorrectHorse9!",passwordConfirmation:"CorrectHorse9!",termsAccepted:true,privacyAccepted:true,riskAccepted:true};expect(registrationSchema.parse(valid).email).toBe("ada@example.com");expect(registrationSchema.safeParse({...valid,password:"weak",passwordConfirmation:"weak"}).success).toBe(false);expect(registrationSchema.safeParse({...valid,passwordConfirmation:"DifferentHorse9!"}).success).toBe(false);});
 it("requires a valid login email and bounded password",()=>{expect(loginSchema.safeParse({email:"bad",password:"x"}).success).toBe(false);expect(loginSchema.safeParse({email:"user@example.com",password:"x"}).success).toBe(true);});
 it("enforces bank receipt presence, type, and size",()=>{const base={method:"bank_transfer",amount:"100.00",senderName:"Ada",externalReference:"BANK-1",userNote:""};const valid=new File([new Uint8Array([0xff,0xd8,0xff])],"receipt.jpg",{type:"image/jpeg"});expect(paymentFormSchema.safeParse({...base,receipt:valid}).success).toBe(true);expect(paymentFormSchema.safeParse({...base,receipt:null}).success).toBe(false);const large=new File([new Uint8Array(MAX_RECEIPT_BYTES+1)],"receipt.pdf",{type:"application/pdf"});expect(paymentFormSchema.safeParse({...base,receipt:large}).success).toBe(false);const css=new File(["body{}"],"receipt.css",{type:"text/css"});expect(paymentFormSchema.safeParse({...base,receipt:css}).success).toBe(false);});
 it("validates Bitcoin hashes and permits optional receipts",()=>{expect(paymentFormSchema.safeParse({method:"bitcoin",amount:"0.1",senderName:"",externalReference:"a".repeat(64),userNote:"",receipt:null}).success).toBe(true);expect(paymentFormSchema.safeParse({method:"bitcoin",amount:"0.1",senderName:"",externalReference:"bad",userNote:"",receipt:null}).success).toBe(false);});
 it("validates investment identifiers, currency, and positive fixed precision amounts",()=>{expect(investmentRequestSchema.safeParse({planId:"123e4567-e89b-42d3-a456-426614174000",currency:"USD",amount:"10.25"}).success).toBe(true);expect(investmentRequestSchema.safeParse({planId:"bad",currency:"usd",amount:"0"}).success).toBe(false);});
 it("validates bank and Bitcoin withdrawal destinations",()=>{expect(withdrawalSchema.safeParse({method:"bank_transfer",amount:"50",currency:"USD",accountName:"Ada",bankName:"Example Bank",accountNumber:"12345678",userNote:""}).success).toBe(true);expect(withdrawalSchema.safeParse({method:"bitcoin",amount:"0.01",currency:"BTC",bitcoinAddress:"bc1qexampleaddress000000",bitcoinNetwork:"Bitcoin",userNote:""}).success).toBe(true);expect(withdrawalSchema.safeParse({method:"bank_transfer",amount:"500",currency:"USD",accountName:"A",bankName:"B",accountNumber:"1"}).success).toBe(false);});
});
